import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { api } from "@/lib/api";
import { Download, FileText, Loader2, Maximize2, Share2 } from "lucide-react";
import { useEffect, useState } from "react";

interface ResumePreviewProps {
  jobId?: string | null;
}

export function ResumePreview({ jobId }: ResumePreviewProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [hasResume, setHasResume] = useState(false);

  useEffect(() => {
    if (jobId) {
      setIsLoading(true);
      // Poll for job completion
      const checkStatus = async () => {
        try {
          const status = await api.getJobStatus(jobId);
          if (status.status === "completed") {
            setHasResume(true);
            setIsLoading(false);
          } else if (status.status === "failed") {
            setIsLoading(false);
          }
        } catch (error) {
          console.error("Error checking job status:", error);
        }
      };

      const interval = setInterval(checkStatus, 2000);
      checkStatus();

      return () => clearInterval(interval);
    }
  }, [jobId]);

  const handleDownloadResume = () => {
    if (jobId) {
      window.open(api.getDownloadUrl(jobId), '_blank');
    }
  };

  const handleDownloadCoverLetter = () => {
    if (jobId) {
      window.open(api.getCoverLetterUrl(jobId), '_blank');
    }
  };

  const handleShare = async () => {
    if (!jobId) return;

    const shareUrl = `${window.location.origin}/output/${jobId}_resume.html`;
    const shareText = 'Check out my resume generated by CareerCraft AI';

    // Try native share API first (mobile devices)
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Resume',
          text: shareText,
          url: shareUrl,
        });
      } catch (err) {
        // User cancelled or error occurred
        console.log('Share cancelled or failed:', err);
      }
    } else {
      // Fallback: Copy link to clipboard
      try {
        await navigator.clipboard.writeText(shareUrl);
        alert('Resume link copied to clipboard!');
      } catch (err) {
        // Fallback: Show link in prompt
        prompt('Copy this link to share your resume:', shareUrl);
      }
    }
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between mb-4 px-2">
        <div>
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Live Preview
          </h3>
          <p className="text-xs text-muted-foreground">Generated Resume & Cover Letter</p>
        </div>
        <div className="flex gap-2">
          {hasResume && (
            <>
              <Button 
                variant="outline" 
                size="sm" 
                className="h-8"
                onClick={handleDownloadCoverLetter}
              >
                <Download className="h-3.5 w-3.5 mr-2" />
                Cover Letter
              </Button>
              <Button 
                size="sm" 
                className="h-8 bg-gradient-to-r from-primary to-purple-600 hover:opacity-90 transition-opacity"
                onClick={handleDownloadResume}
              >
                <Download className="h-3.5 w-3.5 mr-2" />
                Download Resume
              </Button>
            </>
          )}
        </div>
      </div>

      <Card className="flex-1 bg-white/50 backdrop-blur-sm border-2 border-dashed border-muted-foreground/20 overflow-hidden relative group">
        {isLoading && (
          <div className="absolute inset-0 flex items-center justify-center bg-background/80 backdrop-blur-sm z-20">
            <div className="text-center space-y-4">
              <Loader2 className="h-12 w-12 animate-spin text-primary mx-auto" />
              <div>
                <p className="text-lg font-semibold">Generating Your Resume</p>
                <p className="text-sm text-muted-foreground">This may take a few minutes...</p>
              </div>
            </div>
          </div>
        )}

        {!isLoading && !hasResume && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="text-center space-y-4 px-4">
              <FileText className="h-16 w-16 text-muted-foreground/30 mx-auto" />
              <div>
                <p className="text-lg font-semibold text-muted-foreground">No Resume Yet</p>
                <p className="text-sm text-muted-foreground">
                  Start a conversation with Aria to generate your tailored resume
                </p>
              </div>
            </div>
          </div>
        )}

        {hasResume && (
          <>
            <div className="absolute inset-0 flex items-center justify-center bg-background/50 opacity-0 group-hover:opacity-100 transition-opacity z-10 backdrop-blur-[2px]">
              <div className="flex gap-2">
                <Button 
                  variant="secondary" 
                  size="icon" 
                  className="rounded-full h-12 w-12 shadow-lg"
                  onClick={handleDownloadResume}
                >
                  <Maximize2 className="h-5 w-5" />
                </Button>
                <Button 
                  variant="secondary" 
                  size="icon" 
                  className="rounded-full h-12 w-12 shadow-lg"
                  onClick={handleShare}
                >
                  <Share2 className="h-5 w-5" />
                </Button>
              </div>
            </div>

            <ScrollArea className="h-full">
              {/* Load actual resume HTML in iframe */}
              <iframe
                src={`/output/${jobId}_resume.html`}
                className="w-full h-full border-0"
                title="Resume Preview"
                sandbox="allow-same-origin"
              />
            </ScrollArea>
          </>
        )}
      </Card>
    </div>
  );
}